version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PolyglotGraphQL"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-not9dy7w5utg"
s3_prefix = "PolyglotGraphQL"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

